# Fetch the data and import all libraries

In [33]:
import pandas as pd
import scipy.stats as stats
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
import colorama
from colorama import Fore

In [34]:
df = pd.read_csv('creditcard.csv')
r_state=24

# Data and it's behaviour

In [35]:
df.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [36]:
df.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  1.168375e-15  3.416908e-16 -1.379537e-15  2.074095e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   9.604066e-16  1.487313e-15 -5.556467e-16  1.213481e-16 -2.406331e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.654067e-16 -3.568593e-16  2.578648e-16  4.473266e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   5.340915e-16  1.683437e-15 -3.660091e-16 -1.227390e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [37]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

# Normalise the data

In [38]:
columns_not_normalised=['Class']
columns_to_normalise=[x for x in df.columns if x not in columns_not_normalised]
for i in columns_to_normalise:
    df[i] = ( df[i] - df[i].mean() ) / df[i].std()
df.head()

Time        V1        V2        V3        V4        V5        V6  \
0 -1.996580 -0.694241 -0.044075  1.672771  0.973364 -0.245116  0.347067   
1 -1.996580  0.608495  0.161176  0.109797  0.316522  0.043483 -0.061820   
2 -1.996558 -0.693499 -0.811576  1.169466  0.268231 -0.364571  1.351451   
3 -1.996558 -0.493324 -0.112169  1.182514 -0.609726 -0.007469  0.936148   
4 -1.996537 -0.591329  0.531540  1.021410  0.284655 -0.295015  0.071998   

         V7        V8        V9  ...       V21       V22       V23       V24  \
0  0.193679  0.082637  0.331127  ... -0.024923  0.382854 -0.176911  0.110507   
1 -0.063700  0.071253 -0.232494  ... -0.307376 -0.880075  0.162201 -0.561130   
2  0.639775  0.207372 -1.378673  ...  0.337631  1.063356  1.456317 -1.138090   
3  0.192070  0.316017 -1.262501  ... -0.147443  0.007267 -0.304776 -1.941024   
4  0.479301 -0.226510  0.744325  ... -0.012839  1.100009 -0.220123  0.233250   

        V25       V26       V27       V28    Amount  Class  
0  0.246585 -0.392170  0.330891 -0.063781  0.244964      0  
1  0.320693  0.261069 -0.022256  0.044607 -0.342474      0  
2 -0.628536 -0.288446 -0.137137 -0.181021  1.160684      0  
3  1.241902 -0.460217  0.155396  0.186188  0.140534      0  
4 -0.395201  1.041609  0.543619  0.651815 -0.073403      0  

[5 rows x 31 columns]

# Divide and store data into test and train sets.

In [39]:
x_columns=[x for x in df.columns if x != 'Class']
y_column='Class'

X=df[x_columns]
Y=df[y_column]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15, random_state=r_state)

train_data=pd.concat([X_train,Y_train],axis=1)
test_data=pd.concat([X_test,Y_test],axis=1)

train=train_data.to_csv('train.csv')
test=test_data.to_csv('test.csv')




In [40]:
df=pd.read_csv('train.csv')

# Statistical analysis

Pearson's Correlation

=> correlation close to 1 or -1 is good.

=> higher prob_value determines how accurate correlation is.

=> Nothing interesting is achieved as class is not a numeric data. It is a categorical data that too biased.

In [41]:
dependent_feature='Class'
independent_features=[x for x in df.columns if x != dependent_feature]
for i in independent_features:
    pearsons_coef,prob_value=stats.pearsonr(df[i],df[dependent_feature])
    print(i,": pearsons correlation coefficient = ",pearsons_coef," probability value = ",prob_value)
print("__________________________________________________________________________________________________________________")
print()

Unnamed: 0 : pearsons correlation coefficient =  -0.012232363631552178  probability value =  1.75738648585464e-09
Time : pearsons correlation coefficient =  -0.012835023054461782  probability value =  2.6958078884293564e-10
V1 : pearsons correlation coefficient =  -0.098032517176726  probability value =  0.0
V2 : pearsons correlation coefficient =  0.08997697147125146  probability value =  0.0
V3 : pearsons correlation coefficient =  -0.1872638177500201  probability value =  0.0
V4 : pearsons correlation coefficient =  0.13141047010628928  probability value =  0.0
V5 : pearsons correlation coefficient =  -0.09122713191945098  probability value =  0.0
V6 : pearsons correlation coefficient =  -0.04317660239801924  probability value =  3.052625923214369e-100
V7 : pearsons correlation coefficient =  -0.18553080739408762  probability value =  0.0
V8 : pearsons correlation coefficient =  0.014986503908748313  probability value =  1.6551392374989633e-13
V9 : pearsons correlation coefficient =

Analysis of variance(ANOVA)

=>Large f implies stronger correlation

=>Smaller the p more accurate is the f value. 

=>Columns v1 to v12, v14, v16 to v21 are highly correlated to column Class 

In [42]:
df1=df
df1['Class']=df1['Class'].apply(str)
dependent_feature='Class'
independent_features=[x for x in df.columns if x != dependent_feature]
for i in independent_features:
    df_for_anova=df1[[i,dependent_feature]]
    grouped_for_anova=df_for_anova.groupby(dependent_feature)
    f,p=stats.f_oneway(grouped_for_anova.get_group('1')[i],grouped_for_anova.get_group('0')[i])
    print(i,": f-test = ",f," probability value = ",p)

Unnamed: 0 : f-test =  36.22847448599754  probability value =  1.7573864861224516e-09
Time : f-test =  39.886795770122646  probability value =  2.695807888799931e-10
V1 : f-test =  2349.083847009567  probability value =  0.0
V2 : f-test =  1975.8652812183077  probability value =  0.0
V3 : f-test =  8797.822823067183  probability value =  0.0
V4 : f-test =  4253.921262913979  probability value =  0.0
V5 : f-test =  2031.6169488758424  probability value =  0.0
V6 : f-test =  452.13861226782075  probability value =  3.05262592364974e-100
V7 : f-test =  8629.961454464408  probability value =  0.0
V8 : f-test =  54.382918014081376  probability value =  1.6551392377346052e-13
V9 : f-test =  2278.916513814934  probability value =  0.0
V10 : f-test =  11664.785218963489  probability value =  0.0
V11 : f-test =  6012.082018955749  probability value =  0.0
V12 : f-test =  17567.262536910453  probability value =  0.0
V13 : f-test =  4.090293389849388  probability value =  0.04313125222424229
V14 

In [43]:
useful_features=[x for x in df.columns if x not in ['Time','V13','V15','V22','V23','V24','V25','V26','V27','V28','Amount']]
print(useful_features)

['Unnamed: 0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V14', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'Class']


# Model 

train validation split

In [44]:
df=pd.read_csv('train.csv')
X=df[useful_features]
Y=df['Class']

X_train, X_dev, Y_train, Y_dev = train_test_split(X, Y, test_size=0.18, random_state=r_state)

Outlier fraction

In [45]:

state = np.random.RandomState(24)

valid=Y_train[Y_train==0]
fraud=Y_train[Y_train==1]
outlier_fraction=len(fraud)/float(len(valid))

Model and it's fit

In [46]:
model=IsolationForest(n_estimators=100, max_samples=len(X_train), contamination=outlier_fraction,random_state=state, verbose=0)
model.fit(X_train)
scores_prediction = model.decision_function(X_train)
y_train_pred = model.predict(X_train)

/home/ritapravo/.local/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


Prediction formatting and training evalution

In [47]:
y_train_pred[y_train_pred == 1] = 0
y_train_pred[y_train_pred == -1] = 1
n_errors = (y_train_pred != Y_train).sum()


print("\n\nTraining")
print("__________________________________________________________________________________________\n")
print("Classification Report :")
print(classification_report(Y_train,y_train_pred))
print("__________________________________________________________________________________________\n")
print("Confusion matrix")
print(confusion_matrix(Y_train,y_train_pred))
print("__________________________________________________________________________________________\n")
print("error: ",n_errors) 
print("Accuracy Score :",Fore.RED+str(accuracy_score(Y_train,y_train_pred)))



Training
__________________________________________________________________________________________

Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    198181
           1       0.48      0.48      0.48       328

    accuracy                           1.00    198509
   macro avg       0.74      0.74      0.74    198509
weighted avg       1.00      1.00      1.00    198509

__________________________________________________________________________________________

Confusion matrix
[[198011    170]
 [   169    159]]
__________________________________________________________________________________________

error:  339
Accuracy Score : 0.9982922688643839


Prediction, formatting and validation

In [48]:
y_dev_pred = model.predict(X_dev)
y_dev_pred[y_dev_pred == 1] = 0
y_dev_pred[y_dev_pred == -1] = 1
n_errors = (y_dev_pred != Y_dev).sum()


print("\n\nValidation")
print("_________________________________________________________________________________\n")
print("Classification Report :")
print(classification_report(Y_dev,y_dev_pred))
print("_________________________________________________________________________________\n")
print("Confusion matrix")
print(confusion_matrix(Y_dev,y_dev_pred))
print("_________________________________________________________________________________\n")
print("error: ",n_errors) 
print("Accuracy Score :",Fore.RED+str(accuracy_score(Y_dev,y_dev_pred)))



Validation
_________________________________________________________________________________

Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     43499
           1       0.61      0.55      0.58        77

    accuracy                           1.00     43576
   macro avg       0.80      0.77      0.79     43576
weighted avg       1.00      1.00      1.00     43576

_________________________________________________________________________________

Confusion matrix
[[43472    27]
 [   35    42]]
_________________________________________________________________________________

error:  62
Accuracy Score : 0.9985771984578667


# Testing

Prediction and evaluation for testing dataset

In [22]:
df1=pd.read_csv('test.csv')
X_test=df1[useful_features]
Y_test=df1['Class']

y_test_pred = model.predict(X_test)
y_test_pred[y_test_pred == 1] = 0
y_test_pred[y_test_pred == -1] = 1
n_errors = (y_test_pred != Y_test).sum()


print("\n")
print("Testing evalutaion")
print("_____________________________________________________________________________________________\n")
print("Confusion matrix")
print(confusion_matrix(Y_test,y_test_pred))
print("_____________________________________________________________________________________________\n")
print("Classification Report :")
print(classification_report(Y_test,y_test_pred))
print("_____________________________________________________________________________________________\n")
print("error: ",n_errors) 
print("Accuracy Score: ",Fore.RED+str(accuracy_score(Y_test,y_test_pred)))




Testing evalutaion
_____________________________________________________________________________________________

Confusion matrix
[[42596    39]
 [   44    43]]
_____________________________________________________________________________________________

Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     42635
           1       0.52      0.49      0.51        87

    accuracy                           1.00     42722
   macro avg       0.76      0.75      0.75     42722
weighted avg       1.00      1.00      1.00     42722

_____________________________________________________________________________________________

error:  83
Accuracy Score:  0.9980572070595946


# Local Outlier Factor

In [31]:
from sklearn.neighbors import LocalOutlierFactor

model2=LocalOutlierFactor(n_neighbors=10, algorithm='auto', 
                                               leaf_size=30, metric='minkowski',
                                               p=2, metric_params=None, contamination=outlier_fraction)

y_pred2 = model2.fit_predict(X)
# scores_prediction2 = model2.decision_function(X_train)
# y_train_pred2 = model2.predict(X_train)



In [32]:
#y_pred2 = y_train_pred2
y_pred2[y_pred2 == 1] = 0
y_pred2[y_pred2 == -1] = 1
n_errors2 = (y_pred2 != Y).sum()
print(n_errors2)

print("\n\nTraining")
print("__________________________________________________________________________________________\n")
print("Classification Report :")
print(classification_report(Y,y_pred2))
print("__________________________________________________________________________________________\n")
print("Confusion matrix")
print(confusion_matrix(Y,y_pred2))
print("__________________________________________________________________________________________\n")
print("error: ",n_errors2) 
print("Accuracy Score :",Fore.RED+str(accuracy_score(Y,y_pred2)))

626


Training
__________________________________________________________________________________________

Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    241680
           1       0.22      0.22      0.22       405

    accuracy                           1.00    242085
   macro avg       0.61      0.61      0.61    242085
weighted avg       1.00      1.00      1.00    242085

__________________________________________________________________________________________

Confusion matrix
[[241369    311]
 [   315     90]]
__________________________________________________________________________________________

error:  626
Accuracy Score : 0.997414131400128
